// TODO: BETTER SEMANTIC NAMES HERE
export const CHANGE_KEYBOARD_LOCK = 'CHANGE_KEYBOARD_LOCK'

export const CHANGE_COPY_WATCHER = 'CHANGE_COPY_WATCHER'
export const CHANGE_COPY_VALUE = 'CHANGE_COPY_VALUE'

export const CHANGE_PASTE_WATCHER = 'CHANGE_PASTE_WATCHER'
export const CHANGE_PASTE_VALUE = 'CHANGE_PASTE_VALUE'
export const CHANGE_PASTE_PROGRESS = 'CHANGE_PASTE_PROGRESS'

export const CHANGE_TRANSACTION = 'CHANGE_TRANSACTION'

export const CHANGE_ERROR = 'CHANGE_ERROR'

export const UPDATE_ADDRESS_INFO = 'UPDATE_ADDRESS_INFO'








export const CHANGE_TILES = 'CHANGE_TILES'
export const UPDATE_CURRENCY = 'UPDATE_CURRENCY'



export const MUTATION_TYPES = {
  [CHANGE_KEYBOARD_LOCK]: CHANGE_KEYBOARD_LOCK,

  [CHANGE_COPY_WATCHER]: CHANGE_COPY_WATCHER,
  [CHANGE_COPY_VALUE]: CHANGE_COPY_VALUE,

  [CHANGE_PASTE_WATCHER]: CHANGE_PASTE_WATCHER,
  [CHANGE_PASTE_VALUE]: CHANGE_PASTE_VALUE,
  [CHANGE_PASTE_PROGRESS]: CHANGE_PASTE_PROGRESS,

  [CHANGE_TRANSACTION]: CHANGE_TRANSACTION,

  [CHANGE_ERROR]: CHANGE_ERROR,

  [UPDATE_ADDRESS_INFO]: UPDATE_ADDRESS_INFO,



  [CHANGE_TILES]: CHANGE_TILES,
  [UPDATE_CURRENCY]: UPDATE_CURRENCY,
}
