export const SET_CLIPBOARD = 'SET_CLIPBOARD'

export const SET_CURRENCY = 'SET_CURRENCY'

export const SET_CHECKLIST = 'SET_CHECKLIST'

export const SET_CHECKLIST_ITEM_STATE = 'SET_CHECKLIST_ITEM_STATE'
