export const CHANGE_KEYBOARD_LOCK = 'CHANGE_KEYBOARD_LOCK'

export const CHANGE_COPY_WATCHER = 'CHANGE_COPY_WATCHER'
export const CHANGE_COPY_VALUE = 'CHANGE_COPY_VALUE'

export const CHANGE_PASTE_WATCHER = 'CHANGE_PASTE_WATCHER'
export const CHANGE_PASTE_VALUE = 'CHANGE_PASTE_VALUE'




export const UPDATE_PROTECTION_MODE = 'UPDATE_PROTECTION_MODE'

export const UPDATE_CURRENCY = 'UPDATE_CURRENCY'

export const UPDATE_CHECKLIST = 'UPDATE_CHECKLIST'
// export const UPDATE_CHECKLIST_ITEM_STATE = 'UPDATE_CHECKLIST_ITEM_STATE'

export const MUTATION_TYPES = {
  [CHANGE_KEYBOARD_LOCK]: CHANGE_KEYBOARD_LOCK,

  [CHANGE_COPY_WATCHER]: CHANGE_COPY_WATCHER,
  [CHANGE_COPY_VALUE]: CHANGE_COPY_VALUE,

  [CHANGE_PASTE_WATCHER]: CHANGE_PASTE_WATCHER,
  [CHANGE_PASTE_VALUE]: CHANGE_PASTE_VALUE,


  [UPDATE_PROTECTION_MODE]: UPDATE_PROTECTION_MODE,
  [UPDATE_CURRENCY]: UPDATE_CURRENCY,
  [UPDATE_CHECKLIST]: UPDATE_CHECKLIST,
  // [UPDATE_CHECKLIST_ITEM_STATE]: UPDATE_CHECKLIST_ITEM_STATE,
}
