export const SET_CLIPBOARD = 'SET_CLIPBOARD'

export const SET_PROTECTION_MODE = 'SET_PROTECTION_MODE'

export const SET_CURRENCY = 'SET_CURRENCY'

export const SET_CHECKLIST = 'SET_CHECKLIST'
export const SET_CHECKLIST_ITEM_STATE = 'SET_CHECKLIST_ITEM_STATE'

export const MUTATION_TYPES = {
  [SET_CLIPBOARD]: SET_CLIPBOARD,

  [SET_PROTECTION_MODE]: SET_PROTECTION_MODE,

  [SET_CURRENCY]: SET_CURRENCY,

  [SET_CHECKLIST]: SET_CHECKLIST,
  [SET_CHECKLIST_ITEM_STATE]: SET_CHECKLIST_ITEM_STATE,
}
