export const NOTIFICATION_CLICKED = 'NOTIFICATION_CLICKED'

export const CLIPBOARD_CHANGED = 'CLIPBOARD_CHANGED'
export const VALID_ADDRESS_COPIED = 'VALID_ADDRESS_COPIED'

export const START_PASTE_WATCH = 'START_PASTE_WATCH'
export const PASTE_WATCH_STARTED = 'PASTE_WATCH_STARTED'

export const PASTE_STARTED = 'PASTE_STARTED'
export const PASTE_FINISHED = 'PASTE_FINISHED'

export const STOP_PASTE_WATCH = 'STOP_PASTE_WATCH'
export const PASTE_WATCH_STOPPED = 'PASTE_WATCH_STOPPED'

export const LOCK_KEYBOARD = 'LOCK_KEYBOARD'
export const KEYBOARD_LOCKED = 'KEYBOARD_LOCKED'

export const UNLOCK_KEYBOARD = 'UNLOCK_KEYBOARD'
export const KEYBOARD_UNLOCKED = 'KEYBOARD_UNLOCKED'

export const EVENT_TYPES = {
  [NOTIFICATION_CLICKED]: NOTIFICATION_CLICKED,

  [CLIPBOARD_CHANGED]: CLIPBOARD_CHANGED,
  [VALID_ADDRESS_COPIED]: VALID_ADDRESS_COPIED,

  [START_PASTE_WATCH]: START_PASTE_WATCH,
  [PASTE_WATCH_STARTED]: PASTE_WATCH_STARTED,

  [PASTE_STARTED]: PASTE_STARTED,
  [PASTE_FINISHED]: PASTE_FINISHED,

  [STOP_PASTE_WATCH]: STOP_PASTE_WATCH,
  [PASTE_WATCH_STOPPED]: PASTE_WATCH_STOPPED,

  [LOCK_KEYBOARD]: LOCK_KEYBOARD,
  [KEYBOARD_LOCKED]: KEYBOARD_LOCKED,

  [UNLOCK_KEYBOARD]: UNLOCK_KEYBOARD,
  [KEYBOARD_UNLOCKED]: KEYBOARD_UNLOCKED,
}
