export const NOTIFICATION_CLICKED = 'NOTIFICATION_CLICKED'
export const CLIPBOARD_CHANGED = 'CLIPBOARD_CHANGED'
export const KEYBOARD_LOCK = 'KEYBOARD_LOCK'
export const KEYBOARD_UNLOCK = 'KEYBOARD_UNLOCK'

export const EVENT_TYPES = {
  [NOTIFICATION_CLICKED]: NOTIFICATION_CLICKED,
  [CLIPBOARD_CHANGED]: CLIPBOARD_CHANGED,
  [KEYBOARD_LOCK]: KEYBOARD_LOCK,
  [KEYBOARD_UNLOCK]: KEYBOARD_UNLOCK,
}
