export const NOTIFICATION_CLICKED = 'NOTIFICATION_CLICKED'
export const CLIPBOARD_CHANGED = 'CLIPBOARD_CHANGED'

export const EVENT_TYPES = {
  [NOTIFICATION_CLICKED]: NOTIFICATION_CLICKED,
  [CLIPBOARD_CHANGED]: CLIPBOARD_CHANGED,
}
